### ISSUE TITLE
Smartmontools requires root?

### ISSUE THREAD

**Issue by adamburgoyne** [thundermagic/rpi_monitoring_with_prometheus#1]
Hey, thanks for the guide on setting up the rPi monitoring! I've mostly got it all working now apart from scheduling the smartmontools scans due to them requiring root. Am I missing something or have you setup the services that trigger it (that creates the text file for prom to read) under your root user?

**Comment by thundermagic** [comment]
Hello
I am glad the guide helped you.
Yes, unfortunately smartmontool requires root privileges. I am running the
service that runs the smartmon script to collect stats and store in a file
as root.
My systemd service file is

*[Unit]*










*Description=Node Exporter smartmon textfile
collectorAfter=network.target[Service]User=rootGroup=rootType=simpleExecStart=/usr/local/bin/run_smartmon.sh[Install]WantedBy=multi-user.target*

And the content of *run_smartmon.sh *is:








*#!/bin/bashwhile true    do        cd
/home/thunder/media_server/textfile_collectors/        ./smartmon.sh >
/textfile_collector_result/smartmon.tmp        mv
/textfile_collector_result/smartmon.tmp
/textfile_collector_result/smartmon.prom        sleep 30    done*

**Comment by adamburgoyne** [comment]
Thanks for the reply. I ended up getting rid of the service and `run_smartmon.sh` and just directly called the `smartmon.sh` script from roots crontab which saves a few steps and gives the same effect. 

Also FYI there's a version of prom/node_exporter for docker available which reduces a few manual steps. So now all you need is to install the optional smartmon and cpu_status tools :)
